version: "3.9"

services:
  postgres:
    image: postgres
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - postgres
    build: ./
    env_file: ./.env
    ports:
      - $PORT:$PORT
